"""Refresh lightweight quest metadata for exported builds; never load sprite resources."""
from pathlib import Path
import json, re
root = Path(__file__).resolve().parents[1]
rows = {}
for path in sorted((root / 'data/monsters').glob('*.tres')):
    source = path.read_text(encoding='utf-8')
    # Only scalar fields consumed by quest generation; preserve subresource IDs and drop order.
    fields = {'id', 'display_name', 'level', 'is_boss', 'zeny_min', 'zeny_max', 'item_id', 'chance', 'min_count', 'max_count', 'drops'}
    lines = []
    for line in source.splitlines():
        if line == '[resource]' or line.startswith('[sub_resource type="Resource"') or line.split(' = ', 1)[0] in fields:
            lines.append(line)
    rows[path.stem] = '\n'.join(lines)
(root / 'scripts/core/monster_quest_catalog.gd').write_text('# Generated by _tools/build_monster_quest_catalog.py. No textures.\nextends RefCounted\nconst SOURCE := ' + json.dumps(rows, ensure_ascii=False, indent=1) + '\n', encoding='utf-8')
print('Quest catalog:', len(rows), 'monsters')
