"""Make small map-card images from existing background assets; leave originals untouched."""
from pathlib import Path
from PIL import Image, ImageOps
import re, json, hashlib
root=Path(__file__).resolve().parents[1]
out=root/'Sprites/ui/map_thumbnails';out.mkdir(parents=True,exist_ok=True)
game=(root/'scripts/core/game.gd').read_text(encoding='utf-8')
maps=dict(re.findall(r'&"([^"\n]+)": "res://(scenes/maps/[^"\n]+\.tscn)"',game))
index={};sources={};missing=[]
for mid,path in maps.items():
    scene=(root/path).read_text(encoding='utf-8')
    for script in re.findall(r'path="res://(scripts/world/[^"\n]+\.gd)"',scene):
        scene += '\n' + (root/script).read_text(encoding='utf-8')
    for background in set(re.findall(r'res://(scenes/world/[^"\n]*background\.tscn)',scene)):
        scene += '\n' + (root/background).read_text(encoding='utf-8')
    textures=re.findall(r'path="res://([^"\n]+\.(?:png|webp|jpg))"',scene)
    candidates=[t for t in textures if '/map/' in t.lower() and 'depth' in t.lower()]
    if not candidates:candidates=[t for t in textures if '/map/' in t.lower() and any(k in t.lower() for k in ['background','backdrop','_bg'])]
    if not candidates:
        missing.append(mid);continue
    source=candidates[0]
    filename=hashlib.sha1(source.encode()).hexdigest()[:12]+'.webp'
    if source not in sources:
        with Image.open(root/source) as image:
            thumb=ImageOps.fit(image.convert('RGB'),(320,180),method=Image.Resampling.LANCZOS)
            thumb.save(out/filename,'WEBP',quality=68,method=6)
        sources[source]=filename
    index[mid]='res://Sprites/ui/map_thumbnails/'+filename
(root/'scripts/ui/map_thumbnail_index.gd').write_text('# Generated by _tools/build_map_thumbnails.py\nextends RefCounted\nconst PATHS := '+json.dumps(index,ensure_ascii=False,indent=1)+'\n',encoding='utf-8')
report=dict(maps=len(index),unique_images=len(sources),bytes=sum((out/f).stat().st_size for f in sources.values()),missing=missing,sources=sources)
(root/'output/map_thumbnail_report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
print(json.dumps({k:v for k,v in report.items() if k!='sources'}))
