# English names: items / monsters / skills / cards / maps (round 162 glossary)
NAMES = {
# skills
"ดาบฟาดทั่ง":"Anvil Cleave","Bash (ฟันแรง)":"Bash","Battle Cry (คำรามศึก)":"Battle Cry","จังหวะคมดาบ":"Blade Rhythm",
"Endure (อดทน)":"Endure","คมตัดพันธะ":"Erasing Cut","ดาบปักอักขระ":"Faultline","First Aid (ปฐมพยาบาล)":"First Aid",
"HP Recovery (ฟื้นฟูร่างกาย)":"HP Recovery","กระโดดผ่ารูน":"Rune Leap Slash","รูนคมสังหาร":"Keen Inscription",
"Rending Wave (คลื่นดาบเปิดแผล)":"Rending Wave","คมยืนยันนาม":"Named Edge","ประกาศนามที่เก้า":"Ninth Inscription",
"กายาไร้พันธะ":"Unbound Vessel","หกคมอักขระ":"Rune Flurry","เกราะอักขระ":"Rune Guard","พุ่งกรีดอักขระ":"Rune Lunge",
"กายารูน":"Runic Vessel","Slash (พุ่งฟัน)":"Slash","Sword Mastery (เชี่ยวชาญดาบ)":"Sword Mastery","พลังเหล็กกล้า":"Tempered Might",
"เงานามร่วมคม":"Twin Inscription","คมดาบไม่สิ้นสุด":"Unbroken Edge","อ่านรอยพันธะ":"Wallbreaker Stance","ฝนดาบผ่าโลก":"Worldcleaver",
# jobs
"Ninth Edge — คมอักขระที่เก้า":"Ninth Edge","มือใหม่":"Novice","Runeblade — อัศวินดาบรูน":"Runeblade",
# monsters (+ boss titles / skills)
"อัศวินคำสั่งสุดท้าย":"Last-Order Knight","ดาบคำสั่งฟาดพื้น":"Order Blade Slam","บาฟโฟเมท":"Baphomet","ราชาปีศาจบาฟโฟเมท":"Baphomet, Demon King",
"เคียวเงามรณะ":"Death Shadow Scythe","บาฟโฟเมทจูเนียร์":"Baphomet Jr.","ผีบึง":"Bog Lurker",
"อัสตรา ผู้รักษาดารา":"Astra, Keeper of the Stars","วงโคจรปิดนาม":"Name-Sealing Orbit","ออโรรา ผู้พิทักษ์มงกุฎ":"Aurora, Guardian of the Crown",
"รุ่งอรุณสุดท้าย":"Last Dawn","โฮรา ผู้คุมชั่วโมง":"Hora, Warden of Hours","ลูกตุ้มย้อนเวลา":"Rewinding Pendulum",
"อีรา ผู้ล่าหลังเงาสะท้อน":"Ira, Hunter Behind the Reflection","เงาไล่ล่า":"Hunting Shadow","นามสูญ ผู้กลืนทะเบียน":"Namelost, Devourer of the Register",
"ทะเบียนลบนาม":"Register of Erasure","เวอร์ดัน ผู้คุมรากพันธนาการ":"Verdan, Jailer of the Binding Roots","คุกราก":"Root Prison",
"สกาลด์ ผู้ขับลำนำพายุ":"Skald, Cantor of the Storm","ลำนำพายุ":"Storm Canto","สุริยราช สิงห์เตาหลอม":"Suryaraj, Lion of the Forge",
"สุริยะล่าเหยื่อ":"Solar Hunt","เซเลน ผู้พยากรณ์กระแสจันทร์":"Selene, Oracle of the Moontide","น้ำขึ้นจันทร์ดับ":"Tide of the Dark Moon",
"เนธรา ผู้ทอสุญญะ":"Nethra, Weaver of the Void","ใยสุญญะ":"Void Web","ยักษ์แบกโซ่":"Chainbound Ogre","ทุบโซ่ตรวน":"Shackle Smash",
"การ์ม ผู้ถูกล่าม":"Garm the Chained","สิ่งที่เฝ้าความจริง":"The One Who Guards the Truth","สายฟ้าจากโซ่":"Chain Lightning",
"ชอนชอน":"Chonchon","สุนัขเถ้าถ่าน":"Cinder Hound","กวางผลึก":"Crystal Stag","ชาร์จพุ่ง":"Charge","ดรอปส์":"Drops","ผีจมน้ำ":"Drowned",
"เสียงสะท้อน":"Echo Wraith","เสียงสะท้อนหลอน":"Haunting Echo","ค้างคาวถ่านไฟ":"Ember Bat","ผู้ทำนายจากเถ้า":"Ash Seer",
"นิมิตเถ้าถ่าน":"Cinder Vision","เสียงที่ถูกลบ":"Erased Voice","แฟเบร":"Fabre","ผู้พิพากษาผู้ตาย":"The Dead Judge",
"ผู้ที่ยังตัดสินตามพงศาวดาร":"He Who Still Judges by the Chronicles","คำพิพากษา":"Verdict","ผู้ข้ามฝั่ง":"Ferryman","พายข้ามฝั่ง":"Crossing Oar",
"โกเลมเตาหลอม":"Forge Golem","พิพากษาเตาหลอม · ห้าทุบลาวา":"Forge Judgment · Five Lava Smashes","หมาป่าน้ำแข็ง":"Frost Wolf",
"ผู้ดูแลสวน":"Garden Keeper","หนามสวนแสง":"Lightgarden Thorns","เพลิงกุลล์ไวก์":"Gullveig's Flame","ผู้ถูกเผาสามครั้ง":"Thrice-Burned",
"เพลิงสามครั้ง":"Threefold Flame","หมาป่าเฮล":"Hel Hound","เอลฟ์กลวง":"Hollow Elf","ศรแสงกลวง":"Hollow Light Arrow","มอดกลวง":"Hollow Moth",
"ฮอร์เน็ต":"Hornet","โทรลล์น้ำแข็ง":"Ice Troll","ขว้างก้อนน้ำแข็ง":"Ice Boulder Toss","ผู้เฝ้าทั่งว่าง":"Empty Anvil Sentinel",
"ผู้ทดสอบ":"The Tester","ทั่งสั่นสะเทือน":"Anvil Tremor","คิงโพริง":"King Poring","ระเบิดเหมือก":"Slime Burst",
"ดอกไม้กลืนแสง":"Light-Eater Bloom","ละอองแสง":"Light Spores","ผู้หลุดจากแสง":"The Lightforsaken","เอลฟ์ที่ยังจำได้":"The Elf Who Still Remembers",
"เงาที่จำได้":"Remembered Shadow","ผีเสื้อแสง":"Light Moth","ลูนาติก":"Lunatic","ทากลาวา":"Magma Slug","ผีหมอก":"Mist Ghost",
"หมอกกลืนวิญญาณ":"Soul-Eating Mist","ภูตหมอก":"Mist Sprite","มูนัค":"Munak","ผู้เฝ้านาม":"Name Warden","ลบนาม":"Erase Name",
"งูนิดฮ็อกก์เล็ก":"Nidhogg Spawn","พิษราก":"Root Venom","ผู้คุมเบ้าหลอมคำสาบาน":"Warden of the Oathbreak Crucible","ผู้คุมคำสาบาน":"Oath Warden",
"คำสั่ง: คุกเข่า":"Order: Kneel","ออร์คนักรบ":"Orc Warrior","พิตแมน":"Pitman","อัลฟ์เรืองรอง":"Radiant Alfr",
"ผู้ที่ทำตัวเองเป็นท่อ":"He Who Made Himself a Conduit","ลำแสงจากบน":"Beam from Above","เงาสะท้อน":"Reflection","ภาพสะท้อนฟาด":"Mirror Strike",
"รากเลื้อย":"Root Crawler","ผู้เฝ้ารูน":"Rune Watcher","รูนระเบิด":"Rune Blast","ภูตไร้เสียง":"Silent Wraith","ตั๊กแตนตะกรัน":"Slag Mantis",
"เหยี่ยวหิมะ":"Snow Hawk","แมมมอธหิมะ":"Snow Mammoth","ธารน้ำแข็งกระแทก":"Glacier Crash","ด้วงเหล็ก":"Steel Beetle",
"หรุงนีร์ศิลา":"Stone Hrungnir","ยักษ์ที่ถูกทำให้เป็นอาวุธ":"The Giant Made into a Weapon","เสาศิลารูน":"Rune Stone Pillars",
"ทหารหินยักษ์":"Giant Stone Soldier","หอกศิลาพุ่ง":"Stone Spear Thrust","อสูรสายฟ้า":"Stormscar",
"อสูรสายฟ้า — สิ่งที่ซุ่มอยู่ในรอยสายฟ้า":"Stormscar — What Lurks in the Thunder Scar","สายฟ้าคำราม":"Roaring Thunder",
"หมาป่าหนาม":"Thorn Hound","หนามทะลวงพื้น":"Ground-Piercing Thorns","ผู้พิทักษ์วานีร์":"Vanir Sentinel","ผู้ถือโล่แห่งกำแพง":"Shieldbearer of the Wall",
"กระแทกโล่":"Shield Bash","วิญญาณนักรบเอซีร์":"Aesir War Wraith","สายฟ้าสงคราม":"War Lightning","นางฟ้าน้ำ":"Water Nymph","เพลงกล่อม":"Lullaby",
"ต้นไม้เหี่ยว":"Withered Treant","หมาป่า":"Wolf","ราชินีหนาม":"Thorn Matriarch","ผู้พิทักษ์เตาหลอม":"Forge Guardian","โพริง":"Poring",
# items
"ชุดนักผจญภัย":"Adventurer's Suit","หมวกเอซีร์ขึ้นสนิม":"Rusted Aesir Helm","ดาบสงครามเอซีร์":"Aesir Warblade","หนังสัตว์":"Animal Skin",
"แหวนเถ้า":"Ash Ring","เขาบาฟโฟเมท":"Baphomet Horn","เกราะเปลือกไม้":"Bark Armor","ดาบบาสตาร์ด":"Bastard Sword","เขี้ยวค้างคาว":"Bat Fang",
"เขาด้วงเหล็ก":"Steel Beetle Horn","เข็มขัดหนัง":"Leather Belt","ถ่านไร้อักษร":"Blank Ember","กลีบกลืนแสง":"Light-Eater Petal","รากดอก":"Bloom Root",
"ยาน้ำเงิน":"Blue Potion","ยาคราม":"Indigo Potion","กระดูกบึง":"Bog Bone","เกราะกระดูก":"Bone Armor","ดาบใหญ่กระดูก":"Bone Greatsword",
"พงศาวดารเล่มที่ 7 (ครบเล่ม)":"Chronicle, Volume 7 (Complete)","พงศาวดารเล่มที่ 7 (ครึ่งเล่ม)":"Chronicle, Volume 7 (First Half)",
"พงศาวดารเล่มที่ 7 (อีกครึ่ง)":"Chronicle, Volume 7 (Second Half)","บูทนักรบ":"Warrior Boots","หนังพงหนาม":"Bramble Pelt",
"ใบขวานหัก":"Broken Axe Blade","รูนแตก":"Broken Rune","เข็มกลัด":"Brooch","บัคเลอร์":"Buckler","ผ้าห่อศพเก่า":"Old Burial Cloth",
"เศษเปลือกไม้ไหม้":"Scorched Bark","เกราะปลดคำสั่ง":"Unordered Plate","โล่โซ่ขาด":"Chainbreak Shield","แหวนคำสาบานอิสระ":"Free Oath Signet",
"มงกุฎเลนส์เถ้า":"Ash-Lens Circlet","สนับเท้าตะกรัน":"Slag Greaves","รัดเกล้าวงโคจรดารา":"Astral Orbit Circlet","โล่มงกุฎรุ่งอรุณ":"Dawn Crown Aegis",
"ดาบมงกุฎรุ่งอรุณ":"Dawn Crown Blade","มงกุฎชั่วโมงย้อนกลับ":"Crown of Reversed Hours","ทะเบียนนามที่ยังมีชีวิต":"Living Register",
"ผ้าคลุมผู้ล่าภาพสะท้อน":"Mirror Hunter's Mantle","หน้ากากเงาสะท้อน":"Reflection Mask","แหวนผู้รักษานาม":"Namekeeper's Ring",
"ตราผนึกนามสูญ":"Namelost Seal","เกราะรากพันธนาการ":"Binding Root Cuirass","แก่นหัวใจรากพันธนาการ":"Heart of the Binding Roots",
"จี้ผูกรากสี่คำสัตย์":"Four-Oath Rootbound Pendant","เขี้ยวสุริยราช":"Suryaraj Fang","ระฆังพายุแตกร้าว":"Cracked Storm Bell",
"รองเท้าลำนำพายุ":"Storm Canto Boots","เกราะหัวใจสุริยราช":"Suryaraj Heartplate","จี้กระแสจันทร์":"Moontide Pendant","ผ้าคลุมใยสุญญะ":"Void Web Cloak",
"หมวกผ้า":"Cap","หินสลักลายวานีร์":"Vanir Carved Stone","เกราะโซ่":"Chain Mail","เขาสะสมประจุ":"Charged Horn","แครอทกัดครึ่ง":"Half-Eaten Carrot",
"เขี้ยวหมูป่า":"Boar Fang","เขี้ยวเก็บความร้อน":"Heat-Holding Fang","เสื้อคลุมกันเถ้า":"Cinderward Coat","เคลย์มอร์":"Claymore","แหวนเงิน":"Silver Ring",
"ใบโคลเวอร์":"Clover","ข้อโซ่คำสั่ง":"Command Link","คมท่อแสง":"Conduit Edge","เสื้อผ้าฝ้าย":"Cotton Shirt","เขาผลึก":"Crystal Antler",
"เกราะผลึก":"Crystal Armor","โล่ผลึก":"Crystal Shield","เศษเคียวต้องสาป":"Cursed Scythe Shard","แก่นแสงของดาเกอร์":"Dagr's Light Core",
"ก้อนดินอัด":"Dirt Clump","มงกุฎผีจม":"Drowned Crown","หมวกผีจม":"Drowned Helm","เกราะคนแคระ":"Dwarven Mail","ต่างหู":"Earring",
"แหวนเสียงสะท้อน":"Echo Ring","เศษเสียง":"Echo Shard","เกราะเอลฟ์":"Elven Plate","ผ้าคลุมถ่านไฟ":"Ember Cape","หัวใจเพลิง":"Ember Heart",
"เลนส์อ่านเถ้า":"Ash-Reading Lens","ดาบเพลิงกุลล์ไวก์":"Ember of Gullveig","ปีกถ่านไฟ":"Ember Wing","เอ็มเวเรทาร์คอน":"Emveretarcon",
"หมึกที่ถูกลบ":"Erased Ink","พงศาวดารของเอสกิล":"Eskil's Chronicle","ใยแฟเบร":"Fabre Silk","ฟัลชิออน":"Falchion","หนวดแมลง":"Feeler",
"ดาบไม้พาย":"Oar Blade","ดาบเพลิง":"Flame Sword","ปุยนุ่น":"Fluff","สร้อยแก่นเตาหลอม":"Forge Core Pendant","ดาบเตาหลอม":"Forge Saber",
"เถ้าผู้หลุด":"Forsaken Ash","บทเพลงของฟรีดา":"Frida's Song","ดาบคมน้ำแข็ง":"Frost Edge","เขี้ยวน้ำแข็ง":"Frost Fang","ไขกระดูกแข็ง":"Frost Marrow",
"เสื้อขนหมาป่าน้ำแข็ง":"Frost Wolf Coat","น้ำตาแข็ง":"Frozen Tear","ข้อโซ่การ์ม":"Garm's Chain Link","เขี้ยวการ์ม":"Garm Fang",
"ค้อนสลักของเกอร์ด":"Gerd's Carving Hammer","ด้ายผี":"Ghost Thread","กระดูกยักษ์":"Giant Bone","ผ้าพันคอเด็กยักษ์":"Giant Child's Scarf",
"กีบเท้ายักษ์":"Giant Hoof","ถุงมือ":"Gloves","เศษแก้วเรืองแสง":"Glowing Glass Shard","แผ่นเกราะโกเลม":"Golem Plate","โล่การ์ด":"Guard","การ์ด":"Card",
"แกนผู้พิทักษ์":"Guardian Core","เถ้ากุลล์ไวก์":"Gullveig's Ashes","ขนอ่อนเหยี่ยว":"Hawk Down","กรงเล็บเหยี่ยว":"Hawk Talon",
"จี้หัวใจสายฟ้า":"Lightning Heart Pendant","เศษแก่นไม้":"Heartwood Chip","เขี้ยวเฮล":"Hel Fang","เกราะครึ่งของเฮล":"Hel's Half Plate",
"ตราเฮล":"Hel Seal","ด้ายกลวง":"Hollow Thread","หยดน้ำผึ้ง":"Honey Drop","ผ้าคลุมไหล่":"Hood","เฟืองร้อน":"Hot Gear","ตาหมาเฮล":"Hel Hound Eye",
"เศษหรุงนีร์":"Hrungnir Shard","ดอกน้ำแข็ง":"Ice Bloom","หางปีศาจน้อย":"Imp Tail","หางหมูป่า":"Boar Tail","ใบมีดเหล็กคนแคระ":"Dwarven Iron Blade",
"สนับแข้งเหล็ก":"Iron Greaves","หมวกเหล็ก":"Iron Helm","แร่เหล็ก":"Iron Ore","โล่เหล็ก":"Iron Shield","เจลโลปี้":"Jellopy","หมวกโยตุน":"Jotun Helm",
"ตราโยตุน":"Jotun Seal","ตราผู้พิพากษา":"Judge's Seal","โล่ผู้พิพากษา":"Judge's Shield","ดาบซามู":"Katana","ถุงมือคนสวน":"Keeper's Gloves",
"แผ่นคำสั่งสุดท้าย":"Last Order Plate","หมวกหนัง":"Leather Cap","เสื้อหนัง":"Leather Jacket","รองเท้าหนัง":"Leather Shoes",
"ชื่อที่ทิ้งไว้":"A Name Left Behind","ผลึกแสง":"Light Crystal","ดาบผลึกแสง":"Light Crystal Sword","เกล็ดแสง":"Light Scale","ตราแสง":"Light Seal",
"ผงสายฟ้า":"Lightning Dust","หัวใจสายฟ้า":"Lightning Heart","มงกุฎลโยซาลฟ์":"Ljosalf Circlet","หางกระต่ายขาว":"White Rabbit Tail",
"แกนลาวา":"Magma Core","งาแมมมอธ":"Mammoth Tusk","ขนแมมมอธ":"Mammoth Wool","ผ้าคลุมขนแมมมอธ":"Mammoth Wool Cloak","ดาบตัดบึง":"Marsh Cutter",
"หนามราชินี":"Matriarch Thorn","เนื้อย่าง":"Roast Meat","รองเท้านักขุด":"Miner Boots","หมวกนักขุด":"Miner Helmet","ผงกระจก":"Mirror Dust",
"โล่กระจก":"Mirror Shield","ผ้าคลุมหมอก":"Mist Cloak","แก่นหมอก":"Mist Essence","ดาบหมอก":"Mist Saber","เศษหมอก":"Mist Wisp",
"กรงเล็บขุดดิน":"Mole Claw","ผงมอด":"Moth Dust","ผ้าคลุมปีกมอด":"Moth Wing Cape","ผ้าพันคอ":"Muffler","เศษภาพวาดที่หายไป":"Lost Mural Fragment",
"ดาบนาม":"Name Blade","จี้นาม (สวมใส่)":"Name Pendant (Equip)","สร้อยคอ":"Necklace","เกล็ดงู":"Serpent Scale","ดาบมือใหม่":"Novice Sword",
"ไข่มุกนางฟ้า":"Nymph Pearl","น้ำตาผลึก":"Crystal Tear","เศษไม้พาย":"Oar Splinter","แกนคำสาบานที่แตก":"Broken Oath Core",
"รองเท้าก้าวพ้นคำสั่ง":"Oathstep Boots","เศษบัลลังก์ของโอดิน":"Fragment of Odin's Throne","แหวนของโอดิน":"Odin's Ring","ปิ่นปักผมเก่า":"Old Hairpin",
"วุ้นสีส้ม":"Orange Jelly","ยาส้ม":"Orange Potion","ผ้าโพกหัวออร์ค":"Orc Bandana","เขี้ยวออร์ค":"Orc Tooth","ยางไม้ซีด":"Pale Sap","ฟราคอน":"Phracon",
"เกราะเพลท":"Plate Armor","แกนวุ้นโพริง":"Poring Core","ดาบปริซึม":"Prism Blade","เศษปริซึม":"Prism Shard","แก่นเรืองรอง":"Radiant Core",
"แหวนเรืองรอง":"Radiant Ring","เรเปียร์":"Rapier","ยาแดง":"Red Potion","สมุดลืมสกิล":"Book of Forgotten Skills","น้ำแห่งการเกิดใหม่":"Water of Rebirth",
"ริบบิ้น":"Ribbon","แหวนพลัง":"Ring of Power","ทองแม่น้ำ":"River Gold","รองเท้าข้ามน้ำ":"River Walkers","รองเท้าราก":"Root Boots",
"เส้นใยราก":"Root Fiber","ดาบราก":"Root Sword","ลูกประคำ":"Rosary","ดอกไม้ราชินี":"Royal Bloom","วุ้นราชา":"Royal Jelly","ดาบรูน":"Runic Blade",
"เกราะเกล็ด":"Scale Mail","ดาบผู้พิทักษ์":"Sentinel Blade","แกนผู้พิทักษ์วานีร์":"Vanir Sentinel Core","เกราะผู้พิทักษ์":"Sentinel Plate",
"ผลึกเงา":"Shade Crystal","เกล็ดเงา":"Shadow Flake","ดาบสั้น":"Short Sword","รองเท้าไร้เสียง":"Silent Step","ผ้าคลุมไร้เสียง":"Silent Veil",
"ผงเงิน":"Silver Dust","เคียวแก้วตะกรัน":"Slag Glass Sickle","เมือกร้อน":"Hot Slime","เขาเล็กปีศาจ":"Small Demon Horn","ไลเคนหิมะ":"Snow Lichen",
"เศษหินเจาะอัคนี":"Fire Socket Shard","เศษหินเจาะอัสนี":"Thunder Socket Shard","เศษหินเจาะนิรันดร์":"Eternal Socket Shard",
"หินเจาะอัคนี":"Fire Socket Stone","หินเจาะอัสนี":"Thunder Socket Stone","หินเจาะนิรันดร์":"Eternal Socket Stone","ขนนกวิญญาณ":"Spectral Plume",
"เครื่องรางบ่อน้ำ":"Spring Amulet","ขวดน้ำจากบ่อ":"Spring Vial","กีบกวาง":"Stag Hoof","ดาบเขากวาง":"Stag Horn Saber","เปลือกเหล็กด้วง":"Steel Shell",
"เมือกเหนียว":"Sticky Mucus","เหล็กใน":"Stinger","แกนหินยักษ์":"Giant Stone Core","ดาบหรุงนีร์ศิลา":"Stone Hrungnir Blade","เหรียญตราสายฟ้า":"Storm Medal",
"สร้อยหัวใจสายฟ้า":"Storm Heart Pendant","ดาบรูนอสูรสายฟ้า":"Stormscar Runeblade","เกล็ดอสูรสายฟ้า":"Stormscar Scale","หยดน้ำค้างแสง":"Sun Dew",
"ใบไร้แดด":"Sunless Leaf","ตำราวิหาร":"Temple Primer","เขี้ยวหนาม":"Thorn Fang","โล่หนาม":"Thorn Shield","เศษบัลลังก์":"Throne Splinter",
"พรแห่งสายฟ้า":"Thunder's Blessing","มงกุฎจิ๋ว":"Tiny Crown","ผังส่งนามขึ้นหอ":"Tower Route Chart","รองเท้าโทรลล์":"Troll Boots",
"ดาบผ่าโทรลล์":"Troll Cleaver","หนังโทรลล์":"Troll Hide","ฟันโทรลล์":"Troll Tooth","ดาบไร้พันธะ":"Unbound Blade","กระดูกอาถรรพ์":"Cursed Bone",
"มงกุฎวานีร์":"Vanir Circlet","ตราวานีร์":"Vanir Seal","เศษกำแพง":"Wall Fragment","ดาบใหญ่แห่งกำแพง":"Wall Greatsword","เกราะโล่กำแพง":"Wall Plate",
"โล่หินกำแพง":"Wall Shield","อักษรผู้เฝ้า":"Warden's Letter","เลนส์ผู้เฝ้า":"Watcher Lens","ยาขาว":"White Potion","ปีกแห่งวาลคีรี":"Wing of Valkyrie",
"เปลือกไม้เหี่ยว":"Withered Bark","กรงเล็บหมาป่า":"Wolf Claw","ผ้าคลุมหนังหมาป่า":"Wolf Cloak","เขี้ยวหมาป่า":"Wolf Fang","โล่ไม้":"Wooden Shield",
"ดาบไม้":"Wooden Sword","ผงภูตเรือง":"Glowing Wraith Dust","เพลงของอิลวา":"Ylva's Song",
# places
"ป่าสนธยา":"Twilight Forest","ทุ่งวิหาร":"Temple Fields","ป่าเงาลึก":"Deepshade Forest","ทางขบวนเถ้า":"Ash Procession","มุสเปลเฮม":"Muspelheim",
"เตาหลอมไร้คำสั่ง":"Unwritten Forge","เบ้าหลอมคำสาบาน":"Oathbreak Crucible","วิหารเขาทมิฬใต้ราก":"Blackhorn Rootcrypt",
"วานาเฮม — ใต้บึงหมอกเงิน":"Vanaheim — Beneath Silvermist Marsh","กำแพงที่แตก":"The Broken Wall","โยตุนเฮม":"Jotunheim"," (กลางคืน)":" (Night)",
"โถงภาพวาดน้ำแข็ง":"Frozen Hall","หลุมหัวใจสายฟ้า":"Lightning Heart Crater","เหมืองโซ่คำสั่ง":"Chain Quarry","อัมเบอร์เฮเวน นครใต้เถ้า":"Emberhaven, City Beneath the Ash",
"ทางข้ามเถ้า":"Cinder Crossing","เตาหลอมร้าง":"Cold Forge","สวาร์ทัลฟ์เฮม":"Svartalfheim","ทางสายราก (บทที่ 3)":"Root Road (Chapter 3)",
"สวนผลึก":"Crystal Garden","อัลฟ์เฮม":"Alfheim"," (ร่างจาง)":" (Dim Side)","ลโยซาลฟ์ นครแห่งแสง":"Ljosalf, City of Light","ทะเลสาบกระจก":"Mirror Lake",
"ป่าเงาลึกชั้นใน":"Inner Deepshade Forest","ทางเหล็ก (บทที่ 2)":"Iron Road (Chapter 2)","ป่าที่แสงจาง":"Dimming Wood","วิหารบ่อแสง":"Lightwell Sanctum",
"เอลยุดเนียร์ เมืองของผู้ตาย":"Eljudnir, City of the Dead","นิฟล์เฮม":"Niflheim","ฝั่งหมอกน้ำแข็ง":"Mist Shore","แม่น้ำเกียลล์":"River Gjoll",
"เหมืองถ่านไฟ":"Ember Mine","นิดาเวลลิร์":"Nidavellir","อิกดราซิล":"Yggdrasil","สมรภูมิที่ถูกลืม":"Forgotten Battlefield","วานาเฮม":"Vanaheim",
"ป่าเหี่ยว":"Withered Grove","บ่อน้ำแห่งชีวิต":"Spring of Life","ช่องเขาน้ำแข็ง":"Frost Pass","วานาเฮม นครแห่งราก":"Vanaheim, City of Roots",
"อุทการ์ด นครแห่งยักษ์":"Utgard, City of Giants","ทุ่งหญ้ายักษ์":"Giant Steppe","ประตูของการ์ม":"Garm's Gate","นาสตรอนด์ ฝั่งศพ":"Nastrond, Shore of Corpses",
"บัลลังก์ว่างของโอดิน":"Odin's Empty Throne","โถงแห่งนาม":"Hall of Names","ห้อง GM (ทดสอบ)":"GM Room (Test)","ห้องทดสอบ":"Test Room",
"ทางประกายแสง — อัลฟ์เฮม":"Shimmer Road — Alfheim","ทางเหล็ก":"Iron Road","นิดาเวลลิร์ นครเตาหลอม":"Nidavellir, City of Forges",
"ฝั่งหมอกน้ำแข็ง — นิฟล์เฮม":"Mist Shore — Niflheim","ทางประกายแสง":"Shimmer Road","พรอนเทรา นครแห่งสายฟ้า":"Prontera, City of Thunder",
"ทางสายราก":"Root Road","ลานทดสอบดาบรูน":"Runeblade Proving Ground","บึงหมอกเงิน":"Silvermist Marsh","ช่องเขาน้ำแข็ง — โยตุนเฮม":"Frost Pass — Jotunheim",
"อิกดราซิล จุดพักราก":"Yggdrasil — Root Rest","หอร้อยชั้น":"Hundred-Floor Tower","พรอนเทรา":"Prontera","อุทการ์ด":"Utgard","ลโยซาลฟ์":"Ljosalf",
"อัมเบอร์เฮเวน":"Emberhaven","เอลยุดเนียร์":"Eljudnir","มิดการ์ด":"Midgard","แอสการ์ด":"Asgard","ซีนี":"zeny",
}
# templates (runtime regex) — %d = number, %s = any text
TEMPLATES = {
"อิกดราซิล ชั้น %d":"Yggdrasil Floor %d",
"การ์ด%s":"%s Card",
}
