## DropDirectory — ไอเทมชิ้นนี้หาได้จากไหน (★ รอบ 132 ★ สร้างโดย tools/gen_drop_directory.py — ห้ามแก้มือ)
## ใช้ในหน้าต่างคราฟต์: บอกมอน/แมพ/ร้านที่หาวัตถุดิบ โดยไม่ต้องโหลดไฟล์มอน (ซึ่งลากชีทภาพมาด้วย)
class_name DropDirectory
extends RefCounted

## item_id → [[monster_id, "ชื่อมอน", map_id, โอกาส%, บอส?], ...] เรียงโอกาสมาก→น้อย
const SOURCES := {
	&"adventurer_suit": [[&"lunatic", "ลูนาติก", &"dark_forest", 3.00, false]],
	&"aesir_helm_rusted": [[&"bog_lurker", "ผีบึง", &"silver_marsh", 18.00, false], [&"war_wraith", "วิญญาณนักรบเอซีร์", &"forgotten_battlefield", 12.00, false]],
	&"aesir_warblade": [[&"war_wraith", "วิญญาณนักรบเอซีร์", &"forgotten_battlefield", 3.00, false]],
	&"animal_skin": [[&"wolf", "หมาป่า", &"asgard_forest_2", 55.00, false]],
	&"ash_ring": [[&"gullveig_ember", "เพลิงกุลล์ไวก์", &"spring_of_life", 5.00, true]],
	&"baphomet_horn": [[&"baphomet", "บาฟโฟเมท", &"blackhorn_rootcrypt", 65.00, true]],
	&"bark_armor": [[&"root_crawler", "รากเลื้อย", &"root_road", 3.00, false]],
	&"bastard_sword": [[&"orc_warrior", "ออร์คนักรบ", &"dark_forest_2", 3.00, false]],
	&"bat_fang": [[&"ember_bat", "ค้างคาวถ่านไฟ", &"ember_mine", 20.00, false]],
	&"beetle_horn": [[&"steel_beetle", "ด้วงเหล็ก", &"iron_road", 12.00, false]],
	&"belt": [[&"orc_warrior", "ออร์คนักรบ", &"dark_forest_2", 3.00, false]],
	&"blank_ember": [[&"kiln_sentinel", "ผู้เฝ้าทั่งว่าง", &"unwritten_forge", 100.00, true]],
	&"bloom_petal": [[&"light_eater_bloom", "ดอกไม้กลืนแสง", &"crystal_garden", 45.00, false]],
	&"bloom_root": [[&"light_eater_bloom", "ดอกไม้กลืนแสง", &"crystal_garden", 25.00, false]],
	&"blue_potion": [[&"erased_voice", "เสียงที่ถูกลบ", &"hall_of_names", 20.00, false], [&"light_eater_bloom", "ดอกไม้กลืนแสง", &"crystal_garden", 20.00, false], [&"water_nymph", "นางฟ้าน้ำ", &"mirror_lake", 20.00, false], [&"hollow_moth", "มอดกลวง", &"dimming_wood", 16.00, false], [&"light_moth", "ผีเสื้อแสง", &"shimmer_road", 16.00, false], [&"snow_hawk", "เหยี่ยวหิมะ", &"frost_pass", 14.00, false], [&"mist_sprite", "ภูตหมอก", &"silver_marsh", 12.00, false], [&"silent_wraith", "ภูตไร้เสียง", &"hall_of_silence", 8.00, false]],
	&"bog_bone": [[&"bog_lurker", "ผีบึง", &"silver_marsh", 45.00, false]],
	&"bone_armor": [[&"drowned", "ผีจมน้ำ", &"gjoll_river", 3.00, false], [&"nidhogg_spawn", "งูนิดฮ็อกก์เล็ก", &"nastrond", 3.00, false]],
	&"bone_greatsword": [[&"name_warden", "ผู้เฝ้านาม", &"hall_of_names", 3.00, false]],
	&"boots": [[&"stormscar", "อสูรสายฟ้า", &"thunder_scar", 8.00, true]],
	&"bramble_pelt": [[&"thorn_hound", "หมาป่าหนาม", &"root_road", 15.00, false]],
	&"broken_axe_blade": [[&"orc_warrior", "ออร์คนักรบ", &"dark_forest_2", 30.00, false]],
	&"broken_rune": [[&"rune_watcher", "ผู้เฝ้ารูน", &"hall_of_silence", 40.00, false]],
	&"brooch": [[&"hornet", "ฮอร์เน็ต", &"dark_forest", 3.00, false], [&"wolf", "หมาป่า", &"asgard_forest_2", 3.00, false]],
	&"buckler": [[&"stormscar", "อสูรสายฟ้า", &"thunder_scar", 8.00, true]],
	&"burial_cloth": [[&"munak", "มูนัค", &"dark_forest_2", 30.00, false]],
	&"c7_ash_plate": [[&"oath_warden", "ผู้คุมเบ้าหลอมคำสาบาน", &"oathbreak_crucible", 6.00, true], [&"ash_knight", "อัศวินคำสั่งสุดท้าย", &"ash_procession", 3.00, false]],
	&"c7_chainbreak_shield": [[&"kiln_sentinel", "ผู้เฝ้าทั่งว่าง", &"unwritten_forge", 8.00, true], [&"chainbound_ogre", "ยักษ์แบกโซ่", &"chain_quarry", 3.00, false]],
	&"c7_oathbreak_signet": [[&"oath_warden", "ผู้คุมเบ้าหลอมคำสาบาน", &"oathbreak_crucible", 8.00, true]],
	&"c7_oracle_circlet": [[&"ember_oracle", "ผู้ทำนายจากเถ้า", &"ash_procession", 3.00, false]],
	&"c7_slag_greaves": [[&"slag_mantis", "ตั๊กแตนตะกรัน", &"cinder_crossing", 3.00, false]],
	&"card_ash_knight": [[&"ash_knight", "อัศวินคำสั่งสุดท้าย", &"ash_procession", 0.50, false]],
	&"card_baphomet": [[&"baphomet", "บาฟโฟเมท", &"blackhorn_rootcrypt", 5.00, true]],
	&"card_baphomet_jr": [[&"baphomet_jr", "บาฟโฟเมทจูเนียร์", &"blackhorn_rootcrypt", 0.65, false]],
	&"card_bog_lurker": [[&"bog_lurker", "ผีบึง", &"silver_marsh", 0.50, false]],
	&"card_chainbound_ogre": [[&"chainbound_ogre", "ยักษ์แบกโซ่", &"chain_quarry", 0.50, false]],
	&"card_chained_garm": [[&"chained_garm", "การ์ม ผู้ถูกล่าม", &"garm_gate", 5.00, true]],
	&"card_chonchon": [[&"chonchon", "ชอนชอน", &"asgard_forest_2", 0.83, false]],
	&"card_cinder_hound": [[&"cinder_hound", "สุนัขเถ้าถ่าน", &"cinder_crossing", 0.50, false]],
	&"card_crystal_stag": [[&"crystal_stag", "กวางผลึก", &"shimmer_road", 0.50, false]],
	&"card_drops": [[&"drops", "ดรอปส์", &"prontera_field", 0.87, false]],
	&"card_drowned": [[&"drowned", "ผีจมน้ำ", &"gjoll_river", 0.50, false]],
	&"card_echo_wraith": [[&"echo_wraith", "เสียงสะท้อน", &"frozen_hall", 0.50, false]],
	&"card_ember_bat": [[&"ember_bat", "ค้างคาวถ่านไฟ", &"ember_mine", 0.70, false]],
	&"card_ember_oracle": [[&"ember_oracle", "ผู้ทำนายจากเถ้า", &"ash_procession", 0.50, false]],
	&"card_erased_voice": [[&"erased_voice", "เสียงที่ถูกลบ", &"hall_of_names", 0.50, false]],
	&"card_fabre": [[&"fabre", "แฟเบร", &"prontera_field", 0.89, false]],
	&"card_false_judge": [[&"false_judge", "ผู้พิพากษาผู้ตาย", &"nastrond", 5.00, true]],
	&"card_ferryman": [[&"ferryman", "ผู้ข้ามฝั่ง", &"gjoll_river", 0.50, false]],
	&"card_forge_golem": [[&"forge_golem", "โกเลมเตาหลอม", &"hall_of_silence", 0.66, false]],
	&"card_forge_guardian": [[&"forge_guardian", "ผู้พิทักษ์เตาหลอม", &"cold_forge", 5.00, true]],
	&"card_frost_wolf": [[&"frost_wolf", "หมาป่าน้ำแข็ง", &"frost_pass", 0.50, false]],
	&"card_garden_keeper": [[&"garden_keeper", "ผู้ดูแลสวน", &"crystal_garden", 0.50, false]],
	&"card_gullveig_ember": [[&"gullveig_ember", "เพลิงกุลล์ไวก์", &"spring_of_life", 5.00, true]],
	&"card_hel_hound": [[&"hel_hound", "หมาป่าเฮล", &"mist_shore", 0.50, false]],
	&"card_hollow_elf": [[&"hollow_elf", "เอลฟ์กลวง", &"dimming_wood", 0.50, false]],
	&"card_hollow_moth": [[&"hollow_moth", "มอดกลวง", &"dimming_wood", 0.50, false]],
	&"card_hornet": [[&"hornet", "ฮอร์เน็ต", &"dark_forest", 0.83, false]],
	&"card_ice_troll": [[&"ice_troll", "โทรลล์น้ำแข็ง", &"giant_steppe", 0.50, false]],
	&"card_kiln_sentinel": [[&"kiln_sentinel", "ผู้เฝ้าทั่งว่าง", &"unwritten_forge", 5.00, true]],
	&"card_king_poring": [[&"king_poring", "คิงโพริง", &"dark_forest", 5.00, true]],
	&"card_light_eater_bloom": [[&"light_eater_bloom", "ดอกไม้กลืนแสง", &"crystal_garden", 0.50, false]],
	&"card_light_forsaken": [[&"light_forsaken", "ผู้หลุดจากแสง", &"dimming_wood", 5.00, true]],
	&"card_light_moth": [[&"light_moth", "ผีเสื้อแสง", &"shimmer_road", 0.50, false]],
	&"card_lunatic": [[&"lunatic", "ลูนาติก", &"dark_forest", 0.86, false]],
	&"card_magma_slug": [[&"magma_slug", "ทากลาวา", &"ember_mine", 0.69, false]],
	&"card_mist_ghost": [[&"mist_ghost", "ผีหมอก", &"mist_shore", 0.50, false]],
	&"card_mist_sprite": [[&"mist_sprite", "ภูตหมอก", &"silver_marsh", 0.50, false]],
	&"card_munak": [[&"munak", "มูนัค", &"dark_forest_2", 0.76, false]],
	&"card_name_warden": [[&"name_warden", "ผู้เฝ้านาม", &"hall_of_names", 0.50, false]],
	&"card_nidhogg_spawn": [[&"nidhogg_spawn", "งูนิดฮ็อกก์เล็ก", &"nastrond", 0.50, false]],
	&"card_oath_warden": [[&"oath_warden", "ผู้คุมเบ้าหลอมคำสาบาน", &"oathbreak_crucible", 5.00, true]],
	&"card_orc_warrior": [[&"orc_warrior", "ออร์คนักรบ", &"dark_forest_2", 0.71, false]],
	&"card_pitman": [[&"pitman", "พิตแมน", &"iron_road", 0.75, false]],
	&"card_poring": [[&"poring", "poring", &"prontera_field", 0.90, false]],
	&"card_radiant_alfr": [[&"radiant_alfr", "อัลฟ์เรืองรอง", &"lightwell_sanctum", 5.00, true]],
	&"card_reflection": [[&"reflection", "เงาสะท้อน", &"mirror_lake", 0.50, false]],
	&"card_root_crawler": [[&"root_crawler", "รากเลื้อย", &"root_road", 0.50, false]],
	&"card_rune_watcher": [[&"rune_watcher", "ผู้เฝ้ารูน", &"hall_of_silence", 0.62, false]],
	&"card_silent_wraith": [[&"silent_wraith", "ภูตไร้เสียง", &"hall_of_silence", 0.64, false]],
	&"card_slag_mantis": [[&"slag_mantis", "ตั๊กแตนตะกรัน", &"cinder_crossing", 0.50, false]],
	&"card_snow_hawk": [[&"snow_hawk", "เหยี่ยวหิมะ", &"frost_pass", 0.50, false]],
	&"card_snow_mammoth": [[&"snow_mammoth", "แมมมอธหิมะ", &"giant_steppe", 0.50, false]],
	&"card_stone_hrungnir": [[&"stone_hrungnir", "หรุงนีร์ศิลา", &"hrungnir_crater", 5.00, true]],
	&"card_stone_soldier": [[&"stone_soldier", "ทหารหินยักษ์", &"frozen_hall", 0.50, false]],
	&"card_stormscar": [[&"stormscar", "อสูรสายฟ้า", &"thunder_scar", 5.00, true]],
	&"card_thorn_hound": [[&"thorn_hound", "หมาป่าหนาม", &"root_road", 0.50, false]],
	&"card_thorn_matriarch": [[&"thorn_matriarch", "ราชินีหนาม", &"forgotten_battlefield", 5.00, true]],
	&"card_vanir_sentinel": [[&"vanir_sentinel", "ผู้พิทักษ์วานีร์", &"withered_grove", 0.50, false]],
	&"card_wall_shieldbearer": [[&"wall_shieldbearer", "ผู้ถือโล่แห่งกำแพง", &"broken_wall", 5.00, true]],
	&"card_war_wraith": [[&"war_wraith", "วิญญาณนักรบเอซีร์", &"forgotten_battlefield", 0.50, false]],
	&"card_water_nymph": [[&"water_nymph", "นางฟ้าน้ำ", &"mirror_lake", 0.50, false]],
	&"card_withered_treant": [[&"withered_treant", "ต้นไม้เหี่ยว", &"withered_grove", 0.50, false]],
	&"card_wolf": [[&"wolf", "หมาป่า", &"asgard_forest_2", 0.80, false]],
	&"carved_stone": [[&"vanir_sentinel", "ผู้พิทักษ์วานีร์", &"withered_grove", 30.00, false]],
	&"chain_mail": [[&"forge_golem", "โกเลมเตาหลอม", &"hall_of_silence", 3.00, false]],
	&"charged_horn": [[&"stormscar", "อสูรสายฟ้า", &"thunder_scar", 30.00, true]],
	&"chewed_carrot": [[&"lunatic", "ลูนาติก", &"dark_forest", 20.00, false]],
	&"chonchon_eye": [[&"chonchon", "ชอนชอน", &"asgard_forest_2", 8.00, false]],
	&"cinder_fang": [[&"cinder_hound", "สุนัขเถ้าถ่าน", &"cinder_crossing", 70.00, false]],
	&"cinderward_coat": [[&"cinder_hound", "สุนัขเถ้าถ่าน", &"cinder_crossing", 3.00, false]],
	&"claymore": [[&"forge_golem", "โกเลมเตาหลอม", &"hall_of_silence", 3.00, false]],
	&"clover": [[&"chonchon", "ชอนชอน", &"asgard_forest_2", 20.00, false]],
	&"command_link": [[&"chainbound_ogre", "ยักษ์แบกโซ่", &"chain_quarry", 70.00, false]],
	&"conduit_edge": [[&"radiant_alfr", "อัลฟ์เรืองรอง", &"lightwell_sanctum", 5.00, true]],
	&"cotton_shirt": [[&"drops", "ดรอปส์", &"prontera_field", 3.00, false], [&"fabre", "แฟเบร", &"prontera_field", 3.00, false]],
	&"crystal_antler": [[&"crystal_stag", "กวางผลึก", &"shimmer_road", 40.00, false]],
	&"crystal_cloak": [[&"garden_keeper", "ผู้ดูแลสวน", &"crystal_garden", 3.00, false]],
	&"crystal_shield": [[&"light_forsaken", "ผู้หลุดจากแสง", &"dimming_wood", 8.00, true], [&"hollow_elf", "เอลฟ์กลวง", &"dimming_wood", 3.00, false]],
	&"cursed_scythe_shard": [[&"baphomet", "บาฟโฟเมท", &"blackhorn_rootcrypt", 30.00, true]],
	&"dirt_clump": [[&"pitman", "พิตแมน", &"iron_road", 30.00, false]],
	&"drowned_crown": [[&"drowned", "ผีจมน้ำ", &"gjoll_river", 3.00, false]],
	&"drowned_helm": [[&"drowned", "ผีจมน้ำ", &"gjoll_river", 40.00, false]],
	&"dwarven_mail": [[&"forge_guardian", "ผู้พิทักษ์เตาหลอม", &"cold_forge", 8.00, true]],
	&"earring": [[&"rune_watcher", "ผู้เฝ้ารูน", &"hall_of_silence", 3.00, false]],
	&"echo_ring": [[&"stone_hrungnir", "หรุงนีร์ศิลา", &"hrungnir_crater", 5.00, true], [&"echo_wraith", "เสียงสะท้อน", &"frozen_hall", 3.00, false]],
	&"echo_shard": [[&"echo_wraith", "เสียงสะท้อน", &"frozen_hall", 40.00, false]],
	&"elven_plate": [[&"light_forsaken", "ผู้หลุดจากแสง", &"dimming_wood", 5.00, true], [&"radiant_alfr", "อัลฟ์เรืองรอง", &"lightwell_sanctum", 5.00, true], [&"hollow_elf", "เอลฟ์กลวง", &"dimming_wood", 3.00, false]],
	&"ember_cape": [[&"ember_bat", "ค้างคาวถ่านไฟ", &"ember_mine", 3.00, false]],
	&"ember_heart": [[&"gullveig_ember", "เพลิงกุลล์ไวก์", &"spring_of_life", 35.00, true]],
	&"ember_lens": [[&"ember_oracle", "ผู้ทำนายจากเถ้า", &"ash_procession", 70.00, false]],
	&"ember_of_gullveig": [[&"gullveig_ember", "เพลิงกุลล์ไวก์", &"spring_of_life", 5.00, true]],
	&"ember_wing": [[&"ember_bat", "ค้างคาวถ่านไฟ", &"ember_mine", 40.00, false]],
	&"emveretarcon": [[&"oath_warden", "ผู้คุมเบ้าหลอมคำสาบาน", &"oathbreak_crucible", 5.00, true], [&"chained_garm", "การ์ม ผู้ถูกล่าม", &"garm_gate", 4.00, true], [&"radiant_alfr", "อัลฟ์เรืองรอง", &"lightwell_sanctum", 3.50, true], [&"gullveig_ember", "เพลิงกุลล์ไวก์", &"spring_of_life", 3.00, true], [&"kiln_sentinel", "ผู้เฝ้าทั่งว่าง", &"unwritten_forge", 3.00, true], [&"stone_hrungnir", "หรุงนีร์ศิลา", &"hrungnir_crater", 3.00, true], [&"baphomet", "บาฟโฟเมท", &"blackhorn_rootcrypt", 2.50, true], [&"false_judge", "ผู้พิพากษาผู้ตาย", &"nastrond", 2.00, true], [&"stormscar", "อสูรสายฟ้า", &"thunder_scar", 2.00, true], [&"forge_guardian", "ผู้พิทักษ์เตาหลอม", &"cold_forge", 1.50, true], [&"light_forsaken", "ผู้หลุดจากแสง", &"dimming_wood", 1.50, true], [&"thorn_matriarch", "ราชินีหนาม", &"forgotten_battlefield", 1.50, true], [&"wall_shieldbearer", "ผู้ถือโล่แห่งกำแพง", &"broken_wall", 1.50, true], [&"king_poring", "คิงโพริง", &"dark_forest", 1.00, true], [&"ash_knight", "อัศวินคำสั่งสุดท้าย", &"ash_procession", 0.80, false], [&"ember_oracle", "ผู้ทำนายจากเถ้า", &"ash_procession", 0.80, false], [&"name_warden", "ผู้เฝ้านาม", &"hall_of_names", 0.70, false], [&"hollow_elf", "เอลฟ์กลวง", &"dimming_wood", 0.60, false], [&"nidhogg_spawn", "งูนิดฮ็อกก์เล็ก", &"nastrond", 0.60, false], [&"reflection", "เงาสะท้อน", &"mirror_lake", 0.50, false], [&"stone_soldier", "ทหารหินยักษ์", &"frozen_hall", 0.50, false], [&"echo_wraith", "เสียงสะท้อน", &"frozen_hall", 0.40, false]],
	&"erased_ink": [[&"erased_voice", "เสียงที่ถูกลบ", &"hall_of_names", 45.00, false]],
	&"fabre_silk": [[&"fabre", "แฟเบร", &"prontera_field", 35.00, false]],
	&"feeler": [[&"fabre", "แฟเบร", &"prontera_field", 15.00, false]],
	&"ferryman_oar_blade": [[&"ferryman", "ผู้ข้ามฝั่ง", &"gjoll_river", 3.00, false]],
	&"flame_sword": [[&"baphomet", "บาฟโฟเมท", &"blackhorn_rootcrypt", 5.00, true]],
	&"fluff": [[&"hornet", "ฮอร์เน็ต", &"dark_forest", 45.00, false]],
	&"forge_core_pendant": [[&"forge_guardian", "ผู้พิทักษ์เตาหลอม", &"cold_forge", 5.00, true]],
	&"forge_saber": [[&"forge_guardian", "ผู้พิทักษ์เตาหลอม", &"cold_forge", 5.00, true]],
	&"forsaken_ash": [[&"light_forsaken", "ผู้หลุดจากแสง", &"dimming_wood", 65.00, true]],
	&"frost_edge": [[&"frost_wolf", "หมาป่าน้ำแข็ง", &"frost_pass", 4.00, false]],
	&"frost_fang": [[&"frost_wolf", "หมาป่าน้ำแข็ง", &"frost_pass", 45.00, false]],
	&"frost_marrow": [[&"drowned", "ผีจมน้ำ", &"gjoll_river", 35.00, false]],
	&"frost_wolf_coat": [[&"frost_wolf", "หมาป่าน้ำแข็ง", &"frost_pass", 3.00, false]],
	&"frozen_tear": [[&"frost_wolf", "หมาป่าน้ำแข็ง", &"frost_pass", 12.00, false]],
	&"garm_chain_link": [[&"chained_garm", "การ์ม ผู้ถูกล่าม", &"garm_gate", 65.00, true]],
	&"garm_fang": [[&"chained_garm", "การ์ม ผู้ถูกล่าม", &"garm_gate", 5.00, true]],
	&"ghost_thread": [[&"mist_ghost", "ผีหมอก", &"mist_shore", 30.00, false]],
	&"giant_bone": [[&"echo_wraith", "เสียงสะท้อน", &"frozen_hall", 30.00, false]],
	&"giant_hoof": [[&"baphomet", "บาฟโฟเมท", &"blackhorn_rootcrypt", 55.00, true]],
	&"glove": [[&"hornet", "ฮอร์เน็ต", &"dark_forest", 3.00, false], [&"thorn_hound", "หมาป่าหนาม", &"root_road", 2.00, false]],
	&"glow_shard": [[&"king_poring", "คิงโพริง", &"dark_forest", 100.00, true]],
	&"golem_plate": [[&"forge_golem", "โกเลมเตาหลอม", &"hall_of_silence", 30.00, false]],
	&"guard": [[&"wolf", "หมาป่า", &"asgard_forest_2", 3.00, false]],
	&"guardian_core": [[&"forge_guardian", "ผู้พิทักษ์เตาหลอม", &"cold_forge", 65.00, true]],
	&"gullveig_ash": [[&"gullveig_ember", "เพลิงกุลล์ไวก์", &"spring_of_life", 65.00, true]],
	&"hawk_down": [[&"snow_hawk", "เหยี่ยวหิมะ", &"frost_pass", 45.00, false]],
	&"hawk_talon": [[&"snow_hawk", "เหยี่ยวหิมะ", &"frost_pass", 15.00, false]],
	&"heart_pendant": [[&"stone_hrungnir", "หรุงนีร์ศิลา", &"hrungnir_crater", 5.00, true]],
	&"heartwood_chip": [[&"withered_treant", "ต้นไม้เหี่ยว", &"withered_grove", 12.00, false]],
	&"hel_fang": [[&"hel_hound", "หมาป่าเฮล", &"mist_shore", 45.00, false]],
	&"hel_half_plate": [[&"chained_garm", "การ์ม ผู้ถูกล่าม", &"garm_gate", 5.00, true], [&"false_judge", "ผู้พิพากษาผู้ตาย", &"nastrond", 5.00, true]],
	&"hollow_thread": [[&"hollow_elf", "เอลฟ์กลวง", &"dimming_wood", 45.00, false]],
	&"honey_drop": [[&"hornet", "ฮอร์เน็ต", &"dark_forest", 15.00, false]],
	&"hood": [[&"munak", "มูนัค", &"dark_forest_2", 3.00, false]],
	&"hot_gear": [[&"forge_golem", "โกเลมเตาหลอม", &"hall_of_silence", 20.00, false]],
	&"hound_eye": [[&"hel_hound", "หมาป่าเฮล", &"mist_shore", 15.00, false]],
	&"hrungnir_shard": [[&"stone_hrungnir", "หรุงนีร์ศิลา", &"hrungnir_crater", 35.00, true]],
	&"ice_bloom": [[&"wall_shieldbearer", "ผู้ถือโล่แห่งกำแพง", &"broken_wall", 35.00, true]],
	&"imp_tail": [[&"baphomet_jr", "บาฟโฟเมทจูเนียร์", &"blackhorn_rootcrypt", 15.00, false]],
	&"insect_wing": [[&"chonchon", "ชอนชอน", &"asgard_forest_2", 40.00, false]],
	&"iron_blade": [[&"steel_beetle", "ด้วงเหล็ก", &"iron_road", 4.00, false]],
	&"iron_greaves": [[&"steel_beetle", "ด้วงเหล็ก", &"iron_road", 3.00, false]],
	&"iron_helm": [[&"orc_warrior", "ออร์คนักรบ", &"dark_forest_2", 3.00, false]],
	&"iron_ore": [[&"forge_golem", "โกเลมเตาหลอม", &"hall_of_silence", 50.00, false], [&"steel_beetle", "ด้วงเหล็ก", &"iron_road", 40.00, false], [&"orc_warrior", "ออร์คนักรบ", &"dark_forest_2", 30.00, false], [&"pitman", "พิตแมน", &"iron_road", 25.00, false], [&"chonchon", "ชอนชอน", &"asgard_forest_2", 12.00, false]],
	&"iron_shield": [[&"steel_beetle", "ด้วงเหล็ก", &"iron_road", 3.00, false]],
	&"jotun_helm": [[&"wall_shieldbearer", "ผู้ถือโล่แห่งกำแพง", &"broken_wall", 8.00, true]],
	&"judge_seal": [[&"false_judge", "ผู้พิพากษาผู้ตาย", &"nastrond", 65.00, true]],
	&"judge_shield": [[&"false_judge", "ผู้พิพากษาผู้ตาย", &"nastrond", 8.00, true], [&"name_warden", "ผู้เฝ้านาม", &"hall_of_names", 3.00, false]],
	&"katana": [[&"stormscar", "อสูรสายฟ้า", &"thunder_scar", 5.00, true]],
	&"keeper_glove": [[&"garden_keeper", "ผู้ดูแลสวน", &"crystal_garden", 40.00, false]],
	&"last_order_plate": [[&"ash_knight", "อัศวินคำสั่งสุดท้าย", &"ash_procession", 70.00, false]],
	&"leather_cap": [[&"chonchon", "ชอนชอน", &"asgard_forest_2", 3.00, false]],
	&"leather_jacket": [[&"king_poring", "คิงโพริง", &"dark_forest", 6.00, true]],
	&"leather_shoes": [[&"lunatic", "ลูนาติก", &"dark_forest", 3.00, false]],
	&"left_name": [[&"ferryman", "ผู้ข้ามฝั่ง", &"gjoll_river", 60.00, false]],
	&"light_crystal_sword": [[&"radiant_alfr", "อัลฟ์เรืองรอง", &"lightwell_sanctum", 5.00, true]],
	&"light_scale": [[&"light_moth", "ผีเสื้อแสง", &"shimmer_road", 45.00, false], [&"hollow_moth", "มอดกลวง", &"dimming_wood", 20.00, false]],
	&"lightning_dust": [[&"stone_hrungnir", "หรุงนีร์ศิลา", &"hrungnir_crater", 65.00, true]],
	&"ljosalf_circlet": [[&"garden_keeper", "ผู้ดูแลสวน", &"crystal_garden", 3.00, false]],
	&"lunatic_tail": [[&"lunatic", "ลูนาติก", &"dark_forest", 30.00, false]],
	&"magma_core": [[&"magma_slug", "ทากลาวา", &"ember_mine", 12.00, false]],
	&"mammoth_tusk": [[&"snow_mammoth", "แมมมอธหิมะ", &"giant_steppe", 40.00, false]],
	&"mammoth_wool": [[&"snow_mammoth", "แมมมอธหิมะ", &"giant_steppe", 45.00, false]],
	&"mammoth_wool_cloak": [[&"snow_mammoth", "แมมมอธหิมะ", &"giant_steppe", 3.00, false]],
	&"marsh_cutter": [[&"thorn_matriarch", "ราชินีหนาม", &"forgotten_battlefield", 5.00, true], [&"bog_lurker", "ผีบึง", &"silver_marsh", 3.00, false]],
	&"matriarch_thorn": [[&"thorn_matriarch", "ราชินีหนาม", &"forgotten_battlefield", 65.00, true]],
	&"meat": [[&"snow_mammoth", "แมมมอธหิมะ", &"giant_steppe", 40.00, false], [&"hel_hound", "หมาป่าเฮล", &"mist_shore", 30.00, false], [&"thorn_hound", "หมาป่าหนาม", &"root_road", 25.00, false], [&"chonchon", "ชอนชอน", &"asgard_forest_2", 3.00, false]],
	&"miner_boots": [[&"pitman", "พิตแมน", &"iron_road", 3.00, false]],
	&"miner_helmet": [[&"pitman", "พิตแมน", &"iron_road", 3.00, false]],
	&"mirror_dust": [[&"reflection", "เงาสะท้อน", &"mirror_lake", 30.00, false]],
	&"mirror_shield": [[&"forge_guardian", "ผู้พิทักษ์เตาหลอม", &"cold_forge", 8.00, true]],
	&"mist_cloak": [[&"mist_sprite", "ภูตหมอก", &"silver_marsh", 2.00, false]],
	&"mist_essence": [[&"mist_sprite", "ภูตหมอก", &"silver_marsh", 40.00, false]],
	&"mist_saber": [[&"mist_ghost", "ผีหมอก", &"mist_shore", 3.00, false]],
	&"mist_shroud": [[&"mist_ghost", "ผีหมอก", &"mist_shore", 3.00, false]],
	&"mist_wisp": [[&"mist_ghost", "ผีหมอก", &"mist_shore", 45.00, false]],
	&"mole_claw": [[&"pitman", "พิตแมน", &"iron_road", 40.00, false]],
	&"moth_dust": [[&"hollow_moth", "มอดกลวง", &"dimming_wood", 45.00, false]],
	&"moth_wing_cape": [[&"light_moth", "ผีเสื้อแสง", &"shimmer_road", 3.00, false]],
	&"muffler": [[&"munak", "มูนัค", &"dark_forest_2", 3.00, false]],
	&"name_blade": [[&"chained_garm", "การ์ม ผู้ถูกล่าม", &"garm_gate", 5.00, true]],
	&"necklace": [[&"steel_beetle", "ด้วงเหล็ก", &"iron_road", 3.00, false]],
	&"nidhogg_scale": [[&"nidhogg_spawn", "งูนิดฮ็อกก์เล็ก", &"nastrond", 45.00, false]],
	&"novice_sword": [[&"drops", "ดรอปส์", &"prontera_field", 3.00, false]],
	&"nymph_pearl": [[&"water_nymph", "นางฟ้าน้ำ", &"mirror_lake", 12.00, false]],
	&"nymph_tear": [[&"water_nymph", "นางฟ้าน้ำ", &"mirror_lake", 40.00, false]],
	&"oar_splinter": [[&"ferryman", "ผู้ข้ามฝั่ง", &"gjoll_river", 40.00, false]],
	&"oath_core": [[&"oath_warden", "ผู้คุมเบ้าหลอมคำสาบาน", &"oathbreak_crucible", 100.00, true]],
	&"odin_ring": [[&"chained_garm", "การ์ม ผู้ถูกล่าม", &"garm_gate", 5.00, true]],
	&"old_hairpin": [[&"munak", "มูนัค", &"dark_forest_2", 25.00, false]],
	&"orange_jelly": [[&"drops", "ดรอปส์", &"prontera_field", 45.00, false]],
	&"orange_potion": [[&"king_poring", "คิงโพริง", &"dark_forest", 60.00, true], [&"bog_lurker", "ผีบึง", &"silver_marsh", 12.00, false], [&"hornet", "ฮอร์เน็ต", &"dark_forest", 10.00, false], [&"magma_slug", "ทากลาวา", &"ember_mine", 10.00, false], [&"ember_bat", "ค้างคาวถ่านไฟ", &"ember_mine", 8.00, false], [&"munak", "มูนัค", &"dark_forest_2", 8.00, false]],
	&"orc_bandana": [[&"orc_warrior", "ออร์คนักรบ", &"dark_forest_2", 12.00, false]],
	&"orc_tooth": [[&"orc_warrior", "ออร์คนักรบ", &"dark_forest_2", 50.00, false]],
	&"pale_sap": [[&"root_crawler", "รากเลื้อย", &"root_road", 15.00, false]],
	&"phracon": [[&"king_poring", "คิงโพริง", &"dark_forest", 5.00, true], [&"thorn_matriarch", "ราชินีหนาม", &"forgotten_battlefield", 5.00, true], [&"light_forsaken", "ผู้หลุดจากแสง", &"dimming_wood", 4.00, true], [&"wall_shieldbearer", "ผู้ถือโล่แห่งกำแพง", &"broken_wall", 4.00, true], [&"baphomet", "บาฟโฟเมท", &"blackhorn_rootcrypt", 3.00, true], [&"forge_guardian", "ผู้พิทักษ์เตาหลอม", &"cold_forge", 3.00, true], [&"gullveig_ember", "เพลิงกุลล์ไวก์", &"spring_of_life", 3.00, true], [&"stormscar", "อสูรสายฟ้า", &"thunder_scar", 3.00, true], [&"rune_watcher", "ผู้เฝ้ารูน", &"hall_of_silence", 0.90, false], [&"vanir_sentinel", "ผู้พิทักษ์วานีร์", &"withered_grove", 0.90, false], [&"hollow_elf", "เอลฟ์กลวง", &"dimming_wood", 0.80, false], [&"orc_warrior", "ออร์คนักรบ", &"dark_forest_2", 0.80, false], [&"stone_soldier", "ทหารหินยักษ์", &"frozen_hall", 0.70, false], [&"baphomet_jr", "บาฟโฟเมทจูเนียร์", &"blackhorn_rootcrypt", 0.60, false], [&"hornet", "ฮอร์เน็ต", &"dark_forest", 0.60, false], [&"magma_slug", "ทากลาวา", &"ember_mine", 0.60, false], [&"wolf", "หมาป่า", &"asgard_forest_2", 0.50, false]],
	&"plate_armor": [[&"baphomet", "บาฟโฟเมท", &"blackhorn_rootcrypt", 8.00, true]],
	&"poring_core": [[&"poring", "poring", &"prontera_field", 8.00, false]],
	&"prism_blade": [[&"reflection", "เงาสะท้อน", &"mirror_lake", 3.00, false]],
	&"prism_shard": [[&"hollow_elf", "เอลฟ์กลวง", &"dimming_wood", 20.00, false]],
	&"radiant_core": [[&"radiant_alfr", "อัลฟ์เรืองรอง", &"lightwell_sanctum", 65.00, true]],
	&"radiant_ring": [[&"radiant_alfr", "อัลฟ์เรืองรอง", &"lightwell_sanctum", 5.00, true]],
	&"rapier": [[&"king_poring", "คิงโพริง", &"dark_forest", 5.00, true]],
	&"red_potion": [[&"lunatic", "ลูนาติก", &"dark_forest", 10.00, false], [&"root_crawler", "รากเลื้อย", &"root_road", 8.00, false], [&"poring", "poring", &"prontera_field", 6.00, false], [&"drops", "ดรอปส์", &"prontera_field", 5.00, false], [&"pitman", "พิตแมน", &"iron_road", 5.00, false]],
	&"ribbon": [[&"lunatic", "ลูนาติก", &"dark_forest", 3.00, false]],
	&"ring": [[&"forge_guardian", "ผู้พิทักษ์เตาหลอม", &"cold_forge", 5.00, true], [&"stormscar", "อสูรสายฟ้า", &"thunder_scar", 5.00, true], [&"baphomet_jr", "บาฟโฟเมทจูเนียร์", &"blackhorn_rootcrypt", 3.00, false]],
	&"river_gold": [[&"name_warden", "ผู้เฝ้านาม", &"hall_of_names", 12.00, false]],
	&"river_walker": [[&"drowned", "ผีจมน้ำ", &"gjoll_river", 3.00, false]],
	&"root_boots": [[&"thorn_hound", "หมาป่าหนาม", &"root_road", 3.00, false]],
	&"root_fiber": [[&"root_crawler", "รากเลื้อย", &"root_road", 45.00, false]],
	&"root_sword": [[&"withered_treant", "ต้นไม้เหี่ยว", &"withered_grove", 3.00, false]],
	&"root_venom": [[&"nidhogg_spawn", "งูนิดฮ็อกก์เล็ก", &"nastrond", 20.00, false]],
	&"rosary": [[&"munak", "มูนัค", &"dark_forest_2", 3.00, false]],
	&"royal_bloom": [[&"thorn_matriarch", "ราชินีหนาม", &"forgotten_battlefield", 30.00, true]],
	&"royal_jelly": [[&"king_poring", "คิงโพริง", &"dark_forest", 65.00, true]],
	&"runic_blade": [[&"rune_watcher", "ผู้เฝ้ารูน", &"hall_of_silence", 3.00, false]],
	&"sandals": [[&"fabre", "แฟเบร", &"prontera_field", 3.00, false]],
	&"scale_mail": [[&"forge_golem", "โกเลมเตาหลอม", &"hall_of_silence", 3.00, false]],
	&"sentinel_blade": [[&"vanir_sentinel", "ผู้พิทักษ์วานีร์", &"withered_grove", 3.00, false]],
	&"sentinel_core": [[&"vanir_sentinel", "ผู้พิทักษ์วานีร์", &"withered_grove", 35.00, false]],
	&"sentinel_plate": [[&"gullveig_ember", "เพลิงกุลล์ไวก์", &"spring_of_life", 8.00, true], [&"vanir_sentinel", "ผู้พิทักษ์วานีร์", &"withered_grove", 3.00, false]],
	&"shade_crystal": [[&"reflection", "เงาสะท้อน", &"mirror_lake", 100.00, false]],
	&"shadow_flake": [[&"reflection", "เงาสะท้อน", &"mirror_lake", 45.00, false]],
	&"short_sword": [[&"chonchon", "ชอนชอน", &"asgard_forest_2", 3.00, false]],
	&"silent_step": [[&"crystal_stag", "กวางผลึก", &"shimmer_road", 3.00, false]],
	&"silent_veil": [[&"silent_wraith", "ภูตไร้เสียง", &"hall_of_silence", 25.00, false]],
	&"silver_dust": [[&"mist_sprite", "ภูตหมอก", &"silver_marsh", 25.00, false]],
	&"slag_sickle": [[&"slag_mantis", "ตั๊กแตนตะกรัน", &"cinder_crossing", 70.00, false]],
	&"slug_slime": [[&"magma_slug", "ทากลาวา", &"ember_mine", 45.00, false]],
	&"small_horn": [[&"baphomet_jr", "บาฟโฟเมทจูเนียร์", &"blackhorn_rootcrypt", 40.00, false]],
	&"snow_lichen": [[&"wall_shieldbearer", "ผู้ถือโล่แห่งกำแพง", &"broken_wall", 65.00, true]],
	&"socket_shard_1": [[&"baphomet", "บาฟโฟเมท", &"blackhorn_rootcrypt", 100.00, true], [&"gullveig_ember", "เพลิงกุลล์ไวก์", &"spring_of_life", 100.00, true], [&"thorn_matriarch", "ราชินีหนาม", &"forgotten_battlefield", 100.00, true], [&"wall_shieldbearer", "ผู้ถือโล่แห่งกำแพง", &"broken_wall", 100.00, true]],
	&"socket_shard_2": [[&"light_forsaken", "ผู้หลุดจากแสง", &"dimming_wood", 100.00, true], [&"radiant_alfr", "อัลฟ์เรืองรอง", &"lightwell_sanctum", 100.00, true], [&"stone_hrungnir", "หรุงนีร์ศิลา", &"hrungnir_crater", 100.00, true]],
	&"socket_shard_3": [[&"chained_garm", "การ์ม ผู้ถูกล่าม", &"garm_gate", 100.00, true], [&"false_judge", "ผู้พิพากษาผู้ตาย", &"nastrond", 100.00, true]],
	&"socket_stone_1": [[&"baphomet", "บาฟโฟเมท", &"blackhorn_rootcrypt", 10.00, true], [&"gullveig_ember", "เพลิงกุลล์ไวก์", &"spring_of_life", 10.00, true], [&"thorn_matriarch", "ราชินีหนาม", &"forgotten_battlefield", 10.00, true], [&"wall_shieldbearer", "ผู้ถือโล่แห่งกำแพง", &"broken_wall", 10.00, true]],
	&"socket_stone_2": [[&"light_forsaken", "ผู้หลุดจากแสง", &"dimming_wood", 10.00, true], [&"radiant_alfr", "อัลฟ์เรืองรอง", &"lightwell_sanctum", 10.00, true], [&"stone_hrungnir", "หรุงนีร์ศิลา", &"hrungnir_crater", 10.00, true]],
	&"socket_stone_3": [[&"chained_garm", "การ์ม ผู้ถูกล่าม", &"garm_gate", 10.00, true], [&"false_judge", "ผู้พิพากษาผู้ตาย", &"nastrond", 10.00, true]],
	&"spectral_plume": [[&"war_wraith", "วิญญาณนักรบเอซีร์", &"forgotten_battlefield", 40.00, false]],
	&"spring_amulet": [[&"gullveig_ember", "เพลิงกุลล์ไวก์", &"spring_of_life", 5.00, true]],
	&"stag_hoof": [[&"crystal_stag", "กวางผลึก", &"shimmer_road", 30.00, false]],
	&"stag_horn_saber": [[&"crystal_stag", "กวางผลึก", &"shimmer_road", 3.00, false]],
	&"steel_shell": [[&"steel_beetle", "ด้วงเหล็ก", &"iron_road", 35.00, false]],
	&"stinger": [[&"hornet", "ฮอร์เน็ต", &"dark_forest", 35.00, false]],
	&"stone_core": [[&"stone_soldier", "ทหารหินยักษ์", &"frozen_hall", 40.00, false]],
	&"stone_hrungnir_blade": [[&"stone_hrungnir", "หรุงนีร์ศิลา", &"hrungnir_crater", 5.00, true]],
	&"storm_medal": [[&"war_wraith", "วิญญาณนักรบเอซีร์", &"forgotten_battlefield", 8.00, false]],
	&"storm_pendant": [[&"stormscar", "อสูรสายฟ้า", &"thunder_scar", 5.00, true]],
	&"storm_runeblade": [[&"stormscar", "อสูรสายฟ้า", &"thunder_scar", 5.00, true]],
	&"storm_scale": [[&"stormscar", "อสูรสายฟ้า", &"thunder_scar", 65.00, true]],
	&"sun_dew": [[&"drops", "ดรอปส์", &"prontera_field", 10.00, false]],
	&"sunless_leaf": [[&"garden_keeper", "ผู้ดูแลสวน", &"crystal_garden", 40.00, false]],
	&"thorn_fang": [[&"thorn_hound", "หมาป่าหนาม", &"root_road", 40.00, false]],
	&"thorn_shield": [[&"thorn_matriarch", "ราชินีหนาม", &"forgotten_battlefield", 5.00, true]],
	&"throne_splinter": [[&"chained_garm", "การ์ม ผู้ถูกล่าม", &"garm_gate", 30.00, true]],
	&"tiny_crown": [[&"king_poring", "คิงโพริง", &"dark_forest", 25.00, true]],
	&"troll_boots": [[&"ice_troll", "โทรลล์น้ำแข็ง", &"giant_steppe", 3.00, false]],
	&"troll_cleaver": [[&"ice_troll", "โทรลล์น้ำแข็ง", &"giant_steppe", 4.00, false]],
	&"troll_hide": [[&"ice_troll", "โทรลล์น้ำแข็ง", &"giant_steppe", 45.00, false]],
	&"troll_tooth": [[&"ice_troll", "โทรลล์น้ำแข็ง", &"giant_steppe", 15.00, false]],
	&"undead_bone": [[&"baphomet_jr", "บาฟโฟเมทจูเนียร์", &"blackhorn_rootcrypt", 45.00, false], [&"munak", "มูนัค", &"dark_forest_2", 40.00, false]],
	&"vanir_circlet": [[&"thorn_matriarch", "ราชินีหนาม", &"forgotten_battlefield", 6.00, true]],
	&"wall_fragment": [[&"stone_soldier", "ทหารหินยักษ์", &"frozen_hall", 45.00, false]],
	&"wall_greatsword": [[&"stone_soldier", "ทหารหินยักษ์", &"frozen_hall", 3.00, false]],
	&"wall_plate": [[&"stone_hrungnir", "หรุงนีร์ศิลา", &"hrungnir_crater", 8.00, true], [&"wall_shieldbearer", "ผู้ถือโล่แห่งกำแพง", &"broken_wall", 8.00, true]],
	&"wall_shield": [[&"wall_shieldbearer", "ผู้ถือโล่แห่งกำแพง", &"broken_wall", 6.00, true], [&"stone_soldier", "ทหารหินยักษ์", &"frozen_hall", 3.00, false]],
	&"warden_letter": [[&"name_warden", "ผู้เฝ้านาม", &"hall_of_names", 45.00, false]],
	&"watcher_lens": [[&"rune_watcher", "ผู้เฝ้ารูน", &"hall_of_silence", 10.00, false]],
	&"white_potion": [[&"chained_garm", "การ์ม ผู้ถูกล่าม", &"garm_gate", 100.00, true], [&"false_judge", "ผู้พิพากษาผู้ตาย", &"nastrond", 100.00, true], [&"forge_guardian", "ผู้พิทักษ์เตาหลอม", &"cold_forge", 100.00, true], [&"gullveig_ember", "เพลิงกุลล์ไวก์", &"spring_of_life", 100.00, true], [&"light_forsaken", "ผู้หลุดจากแสง", &"dimming_wood", 100.00, true], [&"radiant_alfr", "อัลฟ์เรืองรอง", &"lightwell_sanctum", 100.00, true], [&"stone_hrungnir", "หรุงนีร์ศิลา", &"hrungnir_crater", 100.00, true], [&"thorn_matriarch", "ราชินีหนาม", &"forgotten_battlefield", 100.00, true], [&"wall_shieldbearer", "ผู้ถือโล่แห่งกำแพง", &"broken_wall", 100.00, true], [&"baphomet", "บาฟโฟเมท", &"blackhorn_rootcrypt", 70.00, true], [&"ash_knight", "อัศวินคำสั่งสุดท้าย", &"ash_procession", 25.00, false], [&"baphomet_jr", "บาฟโฟเมทจูเนียร์", &"blackhorn_rootcrypt", 25.00, false], [&"chainbound_ogre", "ยักษ์แบกโซ่", &"chain_quarry", 25.00, false], [&"cinder_hound", "สุนัขเถ้าถ่าน", &"cinder_crossing", 25.00, false], [&"ember_oracle", "ผู้ทำนายจากเถ้า", &"ash_procession", 25.00, false], [&"kiln_sentinel", "ผู้เฝ้าทั่งว่าง", &"unwritten_forge", 25.00, true], [&"oath_warden", "ผู้คุมเบ้าหลอมคำสาบาน", &"oathbreak_crucible", 25.00, true], [&"slag_mantis", "ตั๊กแตนตะกรัน", &"cinder_crossing", 25.00, false], [&"nidhogg_spawn", "งูนิดฮ็อกก์เล็ก", &"nastrond", 20.00, false], [&"drowned", "ผีจมน้ำ", &"gjoll_river", 18.00, false], [&"ferryman", "ผู้ข้ามฝั่ง", &"gjoll_river", 18.00, false], [&"hollow_elf", "เอลฟ์กลวง", &"dimming_wood", 18.00, false], [&"mist_ghost", "ผีหมอก", &"mist_shore", 18.00, false], [&"crystal_stag", "กวางผลึก", &"shimmer_road", 16.00, false], [&"garden_keeper", "ผู้ดูแลสวน", &"crystal_garden", 16.00, false], [&"echo_wraith", "เสียงสะท้อน", &"frozen_hall", 15.00, false], [&"reflection", "เงาสะท้อน", &"mirror_lake", 15.00, false], [&"rune_watcher", "ผู้เฝ้ารูน", &"hall_of_silence", 15.00, false], [&"war_wraith", "วิญญาณนักรบเอซีร์", &"forgotten_battlefield", 15.00, false], [&"ice_troll", "โทรลล์น้ำแข็ง", &"giant_steppe", 12.00, false], [&"frost_wolf", "หมาป่าน้ำแข็ง", &"frost_pass", 10.00, false], [&"withered_treant", "ต้นไม้เหี่ยว", &"withered_grove", 10.00, false]],
	&"withered_bark": [[&"withered_treant", "ต้นไม้เหี่ยว", &"withered_grove", 50.00, false]],
	&"wolf_claw": [[&"wolf", "หมาป่า", &"asgard_forest_2", 15.00, false]],
	&"wolf_cloak": [[&"wolf", "หมาป่า", &"asgard_forest_2", 3.00, false]],
	&"wolf_fang": [[&"wolf", "หมาป่า", &"asgard_forest_2", 30.00, false]],
	&"wooden_shield": [[&"fabre", "แฟเบร", &"prontera_field", 3.00, false]],
	&"wooden_sword": [[&"poring", "poring", &"prontera_field", 3.00, false]],
	&"wraith_dust": [[&"silent_wraith", "ภูตไร้เสียง", &"hall_of_silence", 40.00, false]],
}

## item_id → [town_map_id, ...] ที่มีขาย
const SHOPS := {
	&"bark_armor": [&"utgard_town", &"vanir_town"],
	&"bastard_sword": [&"nidavellir_town"],
	&"blue_potion": [&"eljudnir", &"emberhaven", &"ljosalf_city", &"nidavellir_town", &"prontera_town", &"utgard_town", &"vanir_town"],
	&"blue_potion_2": [&"eljudnir", &"emberhaven", &"ljosalf_city", &"utgard_town", &"vanir_town"],
	&"bone_armor": [&"eljudnir"],
	&"c7_ash_plate": [&"emberhaven"],
	&"c7_oracle_circlet": [&"emberhaven"],
	&"c7_slag_greaves": [&"emberhaven"],
	&"cap": [&"prontera_town"],
	&"chain_mail": [&"nidavellir_town"],
	&"cinderward_coat": [&"emberhaven"],
	&"cotton_shirt": [&"prontera_town"],
	&"crystal_cloak": [&"eljudnir", &"ljosalf_city"],
	&"drowned_crown": [&"eljudnir"],
	&"earring": [&"prontera_town"],
	&"emveretarcon": [&"eljudnir", &"ljosalf_city", &"nidavellir_town", &"prontera_town", &"utgard_town", &"vanir_town"],
	&"falchion": [&"prontera_town"],
	&"guard": [&"prontera_town"],
	&"hood": [&"prontera_town"],
	&"iron_blade": [&"nidavellir_town"],
	&"iron_helm": [&"nidavellir_town"],
	&"iron_ore": [&"nidavellir_town"],
	&"iron_shield": [&"nidavellir_town"],
	&"leather_cap": [&"prontera_town"],
	&"leather_jacket": [&"prontera_town"],
	&"leather_shoes": [&"prontera_town"],
	&"ljosalf_circlet": [&"eljudnir", &"ljosalf_city"],
	&"meat": [&"eljudnir", &"ljosalf_city", &"prontera_town", &"utgard_town", &"vanir_town"],
	&"miner_boots": [&"nidavellir_town"],
	&"miner_helmet": [&"nidavellir_town"],
	&"necklace": [&"prontera_town"],
	&"novice_sword": [&"prontera_town"],
	&"orange_potion": [&"eljudnir", &"ljosalf_city", &"nidavellir_town", &"prontera_town", &"utgard_town", &"vanir_town"],
	&"phracon": [&"eljudnir", &"ljosalf_city", &"nidavellir_town", &"prontera_town", &"utgard_town", &"vanir_town"],
	&"prism_blade": [&"eljudnir", &"ljosalf_city"],
	&"red_potion": [&"eljudnir", &"ljosalf_city", &"nidavellir_town", &"prontera_town", &"utgard_town", &"vanir_town"],
	&"reset_skill": [&"prontera_town"],
	&"reset_stat": [&"prontera_town"],
	&"ribbon": [&"prontera_town"],
	&"root_sword": [&"utgard_town", &"vanir_town"],
	&"rosary": [&"nidavellir_town", &"vanir_town"],
	&"sandals": [&"prontera_town"],
	&"scale_mail": [&"nidavellir_town", &"vanir_town"],
	&"short_sword": [&"prontera_town"],
	&"thunder_blessing": [&"prontera_town"],
	&"vanir_circlet": [&"vanir_town"],
	&"wall_shield": [&"ljosalf_city", &"utgard_town"],
	&"white_potion": [&"eljudnir", &"emberhaven", &"ljosalf_city", &"nidavellir_town", &"utgard_town", &"vanir_town"],
	&"wing_of_valkyrie": [&"eljudnir", &"emberhaven", &"ljosalf_city", &"nidavellir_town", &"prontera_town", &"utgard_town", &"vanir_town"],
	&"wooden_shield": [&"prontera_town"],
	&"wooden_sword": [&"prontera_town"],
}


static func sources_of(item_id: StringName) -> Array:
	return SOURCES.get(item_id, [])


static func shops_of(item_id: StringName) -> Array:
	return SHOPS.get(item_id, [])


## ข้อความสั้น ๆ "ดรอปจาก X (แมพ) · Y" หรือ "ขายที่ ..." — ใช้ในหน้าต่างคราฟต์
static func describe(item_id: StringName, max_sources: int = 3) -> String:
	var parts: Array[String] = []
	var n := 0
	for row in sources_of(item_id):
		if n >= max_sources:
			break
		var map_name: String = Game.map_display_name(StringName(row[2])) if String(row[2]) != "" else ""
		parts.append("%s%s%s" % [String(row[1]), " (บอส)" if bool(row[4]) else "", (" — " + map_name) if map_name != "" else ""])
		n += 1
	var towns := shops_of(item_id)
	if towns.size() >= 4:
		parts.append("ขายที่ร้านในเมือง")
	elif not towns.is_empty():
		var names: Array[String] = []
		for t in towns:
			names.append(Game.map_display_name(StringName(t)))
		parts.append("ขายที่ " + " / ".join(names))
	if item_id == &"phracon" or item_id == &"emveretarcon":
		parts.append("ใบประกาศล่าของกิลด์")
	return " · ".join(parts) if not parts.is_empty() else "ยังไม่มีที่มา"
